import Head from "next/head";
import Link from "next/link";
import { useState, useEffect, useContext } from "react";
import { Store } from "../utils/Store";

const Layout = ({ title, children }) => {
    const [date, setDate] = useState();
    const [cartItemsCount, setCartItemsCount] = useState(0);
    const { state, dispatch } = useContext(Store);
    const { cart } = state;

    // console.log(cart);

    useEffect(() => {
        setDate(new Date().getFullYear());
    }, [])

    useEffect(() => {
        setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
    }, [cart.cartItems]);

    return (
        <>
            <Head>
                <title>{title ? title + " - Next-Ahime" : "Next-Ahime"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/cart-variant.png" />
            </Head>

            <div className="flex flex-col justify-between min-h-screen">
                <header>
                    <nav className="flex h-12 justify-between items-center shadow-md px-4">
                        <Link href="/">
                            <a className="text-lg font-bold">next-ahime</a>
                        </Link>

                        <div>
                            <Link href="/cart">
                                <a className="p-2 hover:underline decoration-2">
                                    Cart
                                    {cartItemsCount > 0 && (<span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                                        {cartItemsCount}
                                    </span>)}
                                </a>
                            </Link>

                            <Link href="/login">
                                <a className="p-2 hover:underline decoration-2">
                                    Login
                                </a>
                            </Link>
                        </div>
                    </nav>
                </header>

                <main className="container m-auto mt-4 px-4">{children}</main>

                <footer className="flex h-10 justify-center items-center shadow-inner">
                    <p>Copyright &copy; {date} - next-ahime</p>
                </footer>
            </div>
        </>
    );
};
export default Layout;
