import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect, useContext } from "react";
import { Menu } from "@headlessui/react";

import { ToastContainer } from "react-toastify";
import Cookies from "js-cookie";

import { Store } from "../utils/Store";

import 'react-toastify/dist/ReactToastify.css'
import DropdownLink from "./DropdownLink";

const Layout = ({ title, children }) => {
    const { status, data: session } = useSession();

    console.log(session);

    const [date, setDate] = useState();
    const [cartItemsCount, setCartItemsCount] = useState(0);
    const { state, dispatch } = useContext(Store);
    const { cart } = state;

    // console.log(cart);

    useEffect(() => {
        setDate(new Date().getFullYear());
    }, []);

    useEffect(() => {
        setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
    }, [cart.cartItems]);

    const logoutHandler = () => {
        // Cookies.remove('cart')

        dispatch({type:'RESET_CART'})

        signOut({callbackUrl:'/login'})
    }

    return (
        <>
            <Head>
                <title>{title ? title + " - Next-Ahime" : "Next-Ahime"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/cart-variant.png" />
            </Head>

            <ToastContainer position="top-right" limit={1} />

            <div className="flex flex-col justify-between min-h-screen">
                <header>
                    <nav className="flex h-12 justify-between items-center shadow-md px-4">
                        <Link href="/">
                            <a className="text-lg font-bold">next-ahime</a>
                        </Link>

                        <div>
                            <Link href="/cart">
                                <a className="p-2 hover:underline decoration-2">
                                    Cart
                                    {cartItemsCount > 0 && (
                                        <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                                            {cartItemsCount}
                                        </span>
                                    )}
                                </a>
                            </Link>

                            {status === "loading" ? (
                                "Loading"
                            ) : session?.user ? (
                                <Menu
                                    as="div"
                                    className="relative inline-block text-left"
                                >
                                    <div>
                                        <Menu.Button className="text-blue-600">
                                            {session.user.name}
                                        </Menu.Button>
                                    </div>
                                    <Menu.Items
                                        className="absolute right-0 w-56 origin-top-right 
                                        bg-white
                                        shadow-lg"
                                    >
                                        <Menu.Item>
                                            <DropdownLink
                                                className="dropdown-link"
                                                href="/profile"
                                            >
                                                Profile
                                            </DropdownLink>
                                        </Menu.Item>

                                        <Menu.Item>
                                            <DropdownLink
                                                className="dropdown-link"
                                                href="/order-history"
                                            >
                                                Order History
                                            </DropdownLink>
                                        </Menu.Item>

                                        <Menu.Item>
                                            <a
                                                className="dropdown-link"
                                                href="#"
                                                onClick={logoutHandler}
                                            >
                                                Logout
                                            </a>
                                        </Menu.Item>
                                    </Menu.Items>
                                </Menu>
                            ) : (
                                <Link href="/login">
                                    <a className="p-2 hover:underline decoration-2">
                                        Login
                                    </a>
                                </Link>
                            )}
                        </div>
                    </nav>
                </header>

                <main className="container m-auto mt-4 px-4">{children}</main>

                <footer className="flex h-10 justify-center items-center shadow-inner">
                    <p>Copyright &copy; {date} - next-ahime</p>
                </footer>
            </div>
        </>
    );
};
export default Layout;
